language: python
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' || $TRAVIS_PYTHON_VERSION == '3.5' ]]; then pip install pep8 pylint; fi
script:
  - nosetests --with-coverage --cover-package=fuzzyargparse
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' || $TRAVIS_PYTHON_VERSION == '3.5' ]]; then pep8 --max-line-length=120 fuzzyargparse && pylint -d C fuzzyargparse; fi
after_success: coveralls
